controller_list:
  - name: fake_bot_gp7_controller
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
initial:  # Define initial robot poses.
  - group: bot_gp7
    pose: default_mfg